import { Router } from 'express';
import authRoutes from '../modules/auth/auth.routes.js';
import settingsRoutes from '../modules/settings/settings.routes.js';
import navbarRoutes from '../modules/navbar/navbar.routes.js';
import bannerRoutes from '../modules/banner/banner.routes.js';
import pageRoutes from '../modules/page/page.routes.js';
import footerColumnRoutes from '../modules/footerColumn/footerColumn.routes.js';
import newsletterRoutes from '../modules/newsletter/newsletter.routes.js';
import homepageSectionRoutes from '../modules/homepageSection/homepageSection.routes.js';
import categoryRoutes from '../modules/category/category.routes.js';
import collectionRoutes from '../modules/collection/collection.routes.js';
import brandRoutes from '../modules/brand/brand.routes.js';
import attributeGroupRoutes from '../modules/attributeGroup/attributeGroup.routes.js';
import attributeRoutes from '../modules/attribute/attribute.routes.js';
import attributeValueRoutes from '../modules/attributeValue/attributeValue.routes.js';
import productRoutes from '../modules/product/product.routes.js';
import reviewRoutes from '../modules/review/review.routes.js';
import metalRateRoutes from '../modules/metalRate/metalRate.routes.js';
import mediaRoutes from '../modules/media/media.routes.js';
import inventoryRoutes from '../modules/inventory/inventory.routes.js';
import warehouseRoutes from '../modules/inventory/warehouse.routes.js';
import barcodeRoutes from '../modules/inventory/barcode.routes.js';
import stockAdjustmentRoutes from '../modules/inventory/stockAdjustment.routes.js';
import stockTransferRoutes from '../modules/inventory/stockTransfer.routes.js';
import stockAuditRoutes from '../modules/inventory/stockAudit.routes.js';
import inventoryAlertRoutes from '../modules/inventory/inventoryAlert.routes.js';
import activityLogRoutes from '../modules/activityLog/activityLog.routes.js';
import addressRoutes from '../modules/address/address.routes.js';
import customerRoutes from '../modules/customer/customer.routes.js';
import orderRoutes from '../modules/order/order.routes.js';
import couponRoutes from '../modules/coupon/coupon.routes.js';
import campaignRoutes from '../modules/campaign/campaign.routes.js';
import orderPaymentRoutes from '../modules/order/orderPayment.routes.js';
import orderShipmentRoutes from '../modules/order/orderShipment.routes.js';
import orderReturnRoutes from '../modules/order/orderReturn.routes.js';
import orderRefundRoutes from '../modules/order/orderRefund.routes.js';
import invoiceRoutes from '../modules/order/invoice.routes.js';
import customerContactRoutes from '../modules/customer/customerContact.routes.js';
import customerNoteRoutes from '../modules/customer/customerNote.routes.js';
import customerSegmentRoutes from '../modules/customer/customerSegment.routes.js';
import customerTagRoutes from '../modules/customer/customerTag.routes.js';
import customerWalletRoutes from '../modules/customer/wallet.routes.js';
import customerLoyaltyRoutes from '../modules/customer/loyalty.routes.js';
import customerReferralRoutes from '../modules/customer/customerReferral.routes.js';
import customerPreferenceRoutes from '../modules/customer/customerPreference.routes.js';
import customerNotificationRoutes from '../modules/customer/customerNotification.routes.js';
import supplierRoutes from '../modules/supplier/supplier.routes.js';
import supplierContactRoutes from '../modules/supplier/supplierContact.routes.js';
import supplierAddressRoutes from '../modules/supplier/supplierAddress.routes.js';
import supplierNoteRoutes from '../modules/supplier/supplierNote.routes.js';
import purchaseOrderRoutes from '../modules/purchase/purchaseOrder.routes.js';
import goodsReceiptNoteRoutes from '../modules/purchase/goodsReceiptNote.routes.js';
import supplierPaymentRoutes from '../modules/purchase/supplierPayment.routes.js';
import purchaseReturnRoutes from '../modules/purchase/purchaseReturn.routes.js';
import supplierLedgerRoutes from '../modules/purchase/supplierLedger.routes.js';
import accountRoutes from '../modules/accounting/account.routes.js';
import journalRoutes from '../modules/accounting/journal.routes.js';
import generalLedgerRoutes from '../modules/accounting/generalLedger.routes.js';
import expenseCategoryRoutes from '../modules/accounting/expenseCategory.routes.js';
import expenseRoutes from '../modules/accounting/expense.routes.js';
import taxRateRoutes from '../modules/accounting/taxRate.routes.js';
import receivablesRoutes from '../modules/accounting/receivables.routes.js';
import payablesRoutes from '../modules/accounting/payables.routes.js';
import reportsRoutes from '../modules/accounting/reports.routes.js';
import financialDashboardRoutes from '../modules/accounting/financialDashboard.routes.js';
import savedFilterRoutes from '../modules/reports/savedFilter.routes.js';
import executiveDashboardRoutes from '../modules/reports/executiveDashboard.routes.js';
import salesReportsRoutes from '../modules/reports/salesReports.routes.js';
import purchaseReportsRoutes from '../modules/reports/purchaseReports.routes.js';
import inventoryReportsRoutes from '../modules/reports/inventoryReports.routes.js';
import customerReportsRoutes from '../modules/reports/customerReports.routes.js';
import supplierReportsRoutes from '../modules/reports/supplierReports.routes.js';
import taxReportsRoutes from '../modules/reports/taxReports.routes.js';
import activityReportsRoutes from '../modules/reports/activityReports.routes.js';
import cipEventRoutes from '../modules/cip/event.routes.js';
import cipSessionRoutes from '../modules/cip/session.routes.js';
import cipVisitorRoutes from '../modules/cip/visitor.routes.js';
import cipCampaignSpendRoutes from '../modules/cip/campaignSpend.routes.js';
import cipSegmentationRoutes from '../modules/cip/segmentation.routes.js';
import cipReportsRoutes from '../modules/cip/cipReports.routes.js';
import cipExecutiveDashboardRoutes from '../modules/cip/executiveCipDashboard.routes.js';
import cipPrivacyRoutes from '../modules/cip/privacy.routes.js';
import publicGeoRoutes from '../modules/cip/publicGeo.routes.js';
import storefrontRoutes from '../modules/storefront/storefront.routes.js';
import helpRoutes from '../modules/help/help.routes.js';
import supportRoutes from '../modules/support/support.routes.js';
import issueRoutes from '../modules/issue/issue.routes.js';
import feedbackRoutes from '../modules/feedback/feedback.routes.js';
import supportReportsRoutes from '../modules/reports/supportReports.routes.js';
import broadcastRoutes from '../modules/broadcast/broadcast.routes.js';

const router = Router();

router.use('/auth', authRoutes);
router.use('/settings', settingsRoutes);
router.use('/navbar', navbarRoutes);
router.use('/banners', bannerRoutes);
router.use('/pages', pageRoutes);
router.use('/footer-columns', footerColumnRoutes);
router.use('/newsletter', newsletterRoutes);
router.use('/homepage-sections', homepageSectionRoutes);
router.use('/categories', categoryRoutes);
router.use('/collections', collectionRoutes);
router.use('/brands', brandRoutes);
router.use('/attribute-groups', attributeGroupRoutes);
router.use('/attributes', attributeRoutes);
router.use('/attribute-values', attributeValueRoutes);
router.use('/products', productRoutes);
router.use('/reviews', reviewRoutes);
router.use('/metal-rates', metalRateRoutes);
router.use('/media', mediaRoutes);
router.use('/inventory', inventoryRoutes);
router.use('/warehouses', warehouseRoutes);
router.use('/barcodes', barcodeRoutes);
router.use('/stock-adjustments', stockAdjustmentRoutes);
router.use('/stock-transfers', stockTransferRoutes);
router.use('/stock-audits', stockAuditRoutes);
router.use('/inventory-alerts', inventoryAlertRoutes);
router.use('/activity-logs', activityLogRoutes);
router.use('/addresses', addressRoutes);
router.use('/customers', customerRoutes);
router.use('/orders', orderRoutes);
// Renamed from the old flat "/coupons" mount to the "/promotions" REST
// namespace once Coupon grew a real Campaign hierarchy above it - the
// admin frontend's couponsApi.js base path was updated to match.
router.use('/promotions/coupons', couponRoutes);
router.use('/promotions/campaigns', campaignRoutes);
router.use('/order-payments', orderPaymentRoutes);
router.use('/order-shipments', orderShipmentRoutes);
router.use('/order-returns', orderReturnRoutes);
router.use('/order-refunds', orderRefundRoutes);
router.use('/invoices', invoiceRoutes);
router.use('/customer-contacts', customerContactRoutes);
router.use('/customer-notes', customerNoteRoutes);
router.use('/customer-segments', customerSegmentRoutes);
router.use('/customer-tags', customerTagRoutes);
router.use('/customer-wallet', customerWalletRoutes);
router.use('/customer-loyalty', customerLoyaltyRoutes);
router.use('/customer-referrals', customerReferralRoutes);
router.use('/customer-preferences', customerPreferenceRoutes);
router.use('/customer-notifications', customerNotificationRoutes);
router.use('/suppliers', supplierRoutes);
router.use('/supplier-contacts', supplierContactRoutes);
router.use('/supplier-addresses', supplierAddressRoutes);
router.use('/supplier-notes', supplierNoteRoutes);
router.use('/purchase-orders', purchaseOrderRoutes);
router.use('/goods-receipt-notes', goodsReceiptNoteRoutes);
router.use('/supplier-payments', supplierPaymentRoutes);
router.use('/purchase-returns', purchaseReturnRoutes);
router.use('/supplier-ledger', supplierLedgerRoutes);
router.use('/accounts', accountRoutes);
router.use('/journals', journalRoutes);
router.use('/general-ledger', generalLedgerRoutes);
router.use('/expense-categories', expenseCategoryRoutes);
router.use('/expenses', expenseRoutes);
router.use('/tax-rates', taxRateRoutes);
router.use('/receivables', receivablesRoutes);
router.use('/payables', payablesRoutes);
router.use('/financial-reports', reportsRoutes);
router.use('/financial-dashboard', financialDashboardRoutes);
router.use('/saved-filters', savedFilterRoutes);
router.use('/executive-dashboard', executiveDashboardRoutes);
router.use('/reports/sales', salesReportsRoutes);
router.use('/reports/purchase', purchaseReportsRoutes);
router.use('/reports/inventory', inventoryReportsRoutes);
router.use('/reports/customers', customerReportsRoutes);
router.use('/reports/suppliers', supplierReportsRoutes);
router.use('/reports/tax', taxReportsRoutes);
router.use('/reports/activity', activityReportsRoutes);
router.use('/cip/events', cipEventRoutes);
router.use('/cip/sessions', cipSessionRoutes);
router.use('/cip/visitors', cipVisitorRoutes);
router.use('/cip/campaign-spend', cipCampaignSpendRoutes);
router.use('/cip/segments', cipSegmentationRoutes);
router.use('/cip/reports', cipReportsRoutes);
router.use('/cip/dashboard', cipExecutiveDashboardRoutes);
router.use('/cip/privacy', cipPrivacyRoutes);
router.use('/geo', publicGeoRoutes);
// A logged-in shopper's own cart-checkout/address/order-history surface -
// deliberately its own module/mount point, not folded into /orders or
// /addresses above, since those stay staff-only (see
// storefront.routes.js's header comment) and this is customer-only.
router.use('/storefront', storefrontRoutes);
// Help Center CMS + public read (Phase 3-4) - public browse/search routes
// live in the same module as the admin CMS actions (RBAC-gated per-route,
// same convention as category/product), not split into a separate
// /admin/* namespace this codebase doesn't otherwise use.
router.use('/help', helpRoutes);
// Support tickets - staff queue only; customer-facing creation/reply lives
// under /storefront/support/tickets (storefront.routes.js), same "staff
// route vs. customer route, same underlying service" split coupons/orders
// already use.
router.use('/support', supportRoutes);
router.use('/issues', issueRoutes);
router.use('/feedback', feedbackRoutes);
router.use('/reports/support', supportReportsRoutes);
router.use('/broadcasts', broadcastRoutes);

export default router;
