import {
  LayoutDashboard,
  Gem,
  Tags,
  Layers,
  MapPin,
  Award,
  ListTree,
  SlidersHorizontal,
  Settings,
  Menu,
  PanelBottom,
  Image,
  LayoutTemplate,
  FileText,
  Gauge,
  Boxes,
  Warehouse,
  Barcode,
  ClipboardEdit,
  ArrowLeftRight,
  ClipboardCheck,
  Bell,
  ShoppingCart,
  Truck,
  Undo2,
  BadgeIndianRupee,
  Users,
  Layers3,
  Tag as TagIcon,
  Building2,
  FileBox,
  Landmark,
  ScrollText,
  BookOpen,
  FileBarChart,
  HandCoins,
  Receipt,
  LayoutGrid,
  BarChart3,
  Radar,
  Users2,
  Megaphone,
  Ticket,
  ReceiptText,
  Star,
  Coins,
  Gift,
  HelpCircle,
  LifeBuoy,
  Flag,
  MessageSquare,
  Send,
} from 'lucide-react';

// Single source of truth for the admin sidebar and breadcrumb labels.
// Add an entry here only once its page actually exists - no placeholder links.
export const ADMIN_NAV_ITEMS = [
  {
    label: 'Dashboard',
    path: '/admin/dashboard',
    icon: LayoutDashboard,
  },
  {
    label: 'Products',
    path: '/admin/catalog/products',
    icon: Gem,
    group: 'Catalog',
  },
  {
    label: 'Categories',
    path: '/admin/catalog/categories',
    icon: Tags,
    group: 'Catalog',
  },
  {
    label: 'Collections Dashboard',
    path: '/admin/catalog/collections/dashboard',
    icon: Gauge,
    group: 'Catalog',
  },
  {
    label: 'Collections',
    path: '/admin/catalog/collections',
    icon: Layers,
    group: 'Catalog',
  },
  {
    label: 'Brands',
    path: '/admin/catalog/brands',
    icon: Award,
    group: 'Catalog',
  },
  {
    label: 'Attribute Groups',
    path: '/admin/catalog/attribute-groups',
    icon: ListTree,
    group: 'Catalog',
  },
  {
    label: 'Attributes',
    path: '/admin/catalog/attributes',
    icon: SlidersHorizontal,
    group: 'Catalog',
  },
  {
    label: 'Metal Rates',
    path: '/admin/metal-rates',
    icon: Coins,
    group: 'Catalog',
  },
  {
    label: 'Homepage',
    path: '/admin/cms/homepage',
    icon: LayoutTemplate,
    group: 'CMS',
  },
  {
    label: 'Navbar',
    path: '/admin/cms/navbar',
    icon: Menu,
    group: 'CMS',
  },
  {
    label: 'Footer',
    path: '/admin/cms/footer',
    icon: PanelBottom,
    group: 'CMS',
  },
  {
    label: 'Banners',
    path: '/admin/cms/banners',
    icon: Image,
    group: 'CMS',
  },
  {
    label: 'Pages',
    path: '/admin/cms/pages',
    icon: FileText,
    group: 'CMS',
  },
  {
    label: 'Settings',
    path: '/admin/cms/settings',
    icon: Settings,
    group: 'CMS',
  },
  {
    label: 'Overview',
    path: '/admin/inventory/dashboard',
    icon: Gauge,
    group: 'Inventory',
  },
  {
    label: 'Stock',
    path: '/admin/inventory',
    icon: Boxes,
    group: 'Inventory',
  },
  {
    label: 'Warehouses',
    path: '/admin/inventory/warehouses',
    icon: Warehouse,
    group: 'Inventory',
  },
  {
    label: 'Barcodes',
    path: '/admin/inventory/barcodes',
    icon: Barcode,
    group: 'Inventory',
  },
  {
    label: 'Adjustments',
    path: '/admin/inventory/adjustments',
    icon: ClipboardEdit,
    group: 'Inventory',
  },
  {
    label: 'Transfers',
    path: '/admin/inventory/transfers',
    icon: ArrowLeftRight,
    group: 'Inventory',
  },
  {
    label: 'Audits',
    path: '/admin/inventory/audits',
    icon: ClipboardCheck,
    group: 'Inventory',
  },
  {
    label: 'Alerts',
    path: '/admin/inventory/alerts',
    icon: Bell,
    group: 'Inventory',
  },
  {
    label: 'Overview',
    path: '/admin/orders/dashboard',
    icon: Gauge,
    group: 'Orders',
  },
  {
    label: 'Orders',
    path: '/admin/orders',
    icon: ShoppingCart,
    group: 'Orders',
  },
  {
    label: 'Shipments',
    path: '/admin/orders/shipments',
    icon: Truck,
    group: 'Orders',
  },
  {
    label: 'Returns',
    path: '/admin/orders/returns',
    icon: Undo2,
    group: 'Orders',
  },
  {
    label: 'Refunds',
    path: '/admin/orders/refunds',
    icon: BadgeIndianRupee,
    group: 'Orders',
  },
  {
    label: 'Campaigns',
    path: '/admin/campaigns',
    icon: Gift,
    group: 'Orders',
  },
  {
    label: 'Coupons',
    path: '/admin/coupons',
    icon: Ticket,
    group: 'Orders',
  },
  {
    label: 'Redemptions',
    path: '/admin/coupons/redemptions',
    icon: BarChart3,
    group: 'Orders',
  },
  {
    label: 'Invoices',
    path: '/admin/invoices',
    icon: ReceiptText,
    group: 'Orders',
  },
  {
    label: 'Reviews',
    path: '/admin/reviews',
    icon: Star,
    group: 'Orders',
  },
  {
    label: 'Overview',
    path: '/admin/customers/dashboard',
    icon: Gauge,
    group: 'Customers',
  },
  {
    label: 'Customers',
    path: '/admin/customers',
    icon: Users,
    group: 'Customers',
  },
  {
    label: 'Segments',
    path: '/admin/customers/segments',
    icon: Layers3,
    group: 'Customers',
  },
  {
    label: 'Tags',
    path: '/admin/customers/tags',
    icon: TagIcon,
    group: 'Customers',
  },
  {
    label: 'Overview',
    path: '/admin/purchases/dashboard',
    icon: Gauge,
    group: 'Purchasing',
  },
  {
    label: 'Suppliers',
    path: '/admin/suppliers',
    icon: Building2,
    group: 'Purchasing',
  },
  {
    label: 'Purchase Orders',
    path: '/admin/purchase-orders',
    icon: FileBox,
    group: 'Purchasing',
  },
  {
    label: 'Returns',
    path: '/admin/purchase-returns',
    icon: Undo2,
    group: 'Purchasing',
  },
  {
    label: 'Overview',
    path: '/admin/accounting/dashboard',
    icon: Gauge,
    group: 'Accounting',
  },
  {
    label: 'Chart of Accounts',
    path: '/admin/accounting/accounts',
    icon: Landmark,
    group: 'Accounting',
  },
  {
    label: 'Journals',
    path: '/admin/accounting/journals',
    icon: ScrollText,
    group: 'Accounting',
  },
  {
    label: 'Ledger',
    path: '/admin/accounting/ledger',
    icon: BookOpen,
    group: 'Accounting',
  },
  {
    label: 'Reports',
    path: '/admin/accounting/reports',
    icon: FileBarChart,
    group: 'Accounting',
  },
  {
    label: 'Receivables & Payables',
    path: '/admin/accounting/receivables-payables',
    icon: HandCoins,
    group: 'Accounting',
  },
  {
    label: 'Expenses',
    path: '/admin/accounting/expenses',
    icon: Receipt,
    group: 'Accounting',
  },
  {
    label: 'Executive Dashboard',
    path: '/admin/reports/executive-dashboard',
    icon: LayoutGrid,
    group: 'Reports & BI',
  },
  {
    label: 'Reports Center',
    path: '/admin/reports/center',
    icon: BarChart3,
    group: 'Reports & BI',
  },
  {
    label: 'CIP Dashboard',
    path: '/admin/cip/dashboard',
    icon: Radar,
    group: 'Customer Intelligence',
  },
  {
    label: 'CIP Reports',
    path: '/admin/cip/reports',
    icon: BarChart3,
    group: 'Customer Intelligence',
  },
  {
    label: 'Location Intelligence',
    path: '/admin/cip/locations',
    icon: MapPin,
    group: 'Customer Intelligence',
  },
  {
    label: 'Segments',
    path: '/admin/cip/segments',
    icon: Users2,
    group: 'Customer Intelligence',
  },
  {
    label: 'Campaign Spend',
    path: '/admin/cip/campaign-spend',
    icon: Megaphone,
    group: 'Customer Intelligence',
  },
  {
    label: 'Broadcast',
    path: '/admin/broadcast',
    icon: Send,
    group: 'Customer Intelligence',
  },
  {
    label: 'Help Center',
    path: '/admin/help/articles',
    icon: HelpCircle,
    group: 'Support',
  },
  {
    label: 'Tickets',
    path: '/admin/support/tickets',
    icon: LifeBuoy,
    group: 'Support',
  },
  {
    label: 'Issue Reports',
    path: '/admin/issues',
    icon: Flag,
    group: 'Support',
  },
  {
    label: 'Feedback',
    path: '/admin/feedback',
    icon: MessageSquare,
    group: 'Support',
  },
  {
    label: 'Help Categories',
    path: '/admin/help/categories',
    icon: LayoutGrid,
    group: 'Support',
  },
  {
    label: 'Search Analytics',
    path: '/admin/help/search-analytics',
    icon: BarChart3,
    group: 'Support',
  },
  {
    label: 'Support Settings',
    path: '/admin/support/settings',
    icon: SlidersHorizontal,
    group: 'Support',
  },
];
