// Must match backend/src/modules/issue/issue.constants.js#ISSUE_SUBCATEGORIES_BY_CATEGORY
// exactly - the reason list a customer picks from when reporting a
// problem, scoped per category (Phase 6/9/11/13/14/15/17/19).
export const ISSUE_REASONS_BY_CATEGORY = {
  product: [
    { value: 'incorrect_information', label: 'Incorrect information' },
    { value: 'incorrect_price', label: 'Incorrect price' },
    { value: 'wrong_image', label: 'Wrong image' },
    { value: 'wrong_specification', label: 'Wrong specification' },
    { value: 'size_information_incorrect', label: 'Size information incorrect' },
    { value: 'unavailable_product', label: 'Product unavailable' },
    { value: 'suspicious_information', label: 'Suspicious information' },
    { value: 'other', label: 'Other' },
  ],
  coupon: [
    { value: 'not_applying', label: "Coupon isn't applying" },
    { value: 'minimum_order_not_met', label: 'Minimum order not met' },
    { value: 'expired', label: 'Coupon expired' },
    { value: 'invalid_code', label: 'Invalid code' },
    { value: 'excluded_product', label: 'Product excluded from this offer' },
    { value: 'other', label: 'Other' },
  ],
  order: [
    { value: 'order_delayed', label: 'Order delayed' },
    { value: 'wrong_product', label: 'Wrong product received' },
    { value: 'damaged_product', label: 'Damaged product' },
    { value: 'missing_product', label: 'Missing product' },
    { value: 'incorrect_quantity', label: 'Incorrect quantity' },
    { value: 'invoice_issue', label: 'Invoice issue' },
    { value: 'payment_issue', label: 'Payment issue' },
    { value: 'refund_issue', label: 'Refund issue' },
    { value: 'delivery_issue', label: 'Delivery issue' },
    { value: 'product_quality_issue', label: 'Product quality issue' },
    { value: 'other', label: 'Other' },
  ],
  payment: [
    { value: 'payment_failed', label: 'Payment failed' },
    { value: 'amount_deducted_order_not_placed', label: 'Amount deducted but order not placed' },
    { value: 'duplicate_charge', label: 'Duplicate charge' },
    { value: 'wrong_amount', label: 'Wrong amount charged' },
    { value: 'other', label: 'Other' },
  ],
  shipping: [
    { value: 'delayed_delivery', label: 'Delayed delivery' },
    { value: 'tracking_not_updating', label: 'Tracking not updating' },
    { value: 'wrong_tracking_information', label: 'Wrong tracking information' },
    { value: 'delivery_failed', label: 'Delivery failed' },
    { value: 'package_damaged', label: 'Package damaged' },
    { value: 'package_missing', label: 'Package missing' },
    { value: 'other', label: 'Other' },
  ],
  return: [
    { value: 'damaged', label: 'Damaged' },
    { value: 'wrong_product', label: 'Wrong product' },
    { value: 'size_issue', label: 'Size issue' },
    { value: 'quality_issue', label: 'Quality issue' },
    { value: 'product_mismatch', label: 'Product mismatch' },
    { value: 'missing_certificate', label: 'Missing certificate' },
    { value: 'missing_item', label: 'Missing item' },
    { value: 'other', label: 'Other' },
  ],
  refund: [
    { value: 'refund_delayed', label: 'Refund delayed' },
    { value: 'refund_not_received', label: 'Refund not received' },
    { value: 'wrong_refund_amount', label: 'Wrong refund amount' },
    { value: 'other', label: 'Other' },
  ],
  invoice: [
    { value: 'invoice_missing', label: 'Invoice missing' },
    { value: 'incorrect_amount', label: 'Incorrect amount' },
    { value: 'incorrect_customer_details', label: 'Incorrect customer details' },
    { value: 'incorrect_tax_information', label: 'Incorrect tax information' },
    { value: 'invoice_download_failed', label: 'Invoice download failed' },
    { value: 'other', label: 'Other' },
  ],
  account: [
    { value: 'login_issue', label: 'Login issue' },
    { value: 'otp_issue', label: 'OTP issue' },
    { value: 'profile_update_issue', label: 'Profile update issue' },
    { value: 'suspicious_activity', label: 'Suspicious activity' },
    { value: 'account_security_issue', label: 'Account security issue' },
    { value: 'other', label: 'Other' },
  ],
  cart: [
    { value: 'price_calculation', label: 'Price calculation looks wrong' },
    { value: 'coupon_not_applying', label: "Coupon isn't applying" },
    { value: 'item_missing', label: 'Item missing from cart' },
    { value: 'other', label: 'Other' },
  ],
  checkout: [
    { value: 'address_issue', label: 'Address issue' },
    { value: 'coupon_issue', label: 'Coupon issue' },
    { value: 'pricing_issue', label: 'Pricing issue' },
    { value: 'shipping_issue', label: 'Shipping issue' },
    { value: 'payment_issue', label: 'Payment issue' },
    { value: 'other', label: 'Other' },
  ],
  other: [{ value: 'other', label: 'Other' }],
};
